In [ ]:
import torch
torch.__version__

'2.3.0+cu121'

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get the python number within a tensor (only works with one-element tensors)

scalar.item()

7

In [ ]:
# A Vector

vector=torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
# check shape of vector
vector.shape

torch.Size([2])

In [ ]:
# The MATRIX

MATRIX = torch.tensor([[7, 8],
                     [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Check number of dimensions
MATRIX.ndim

2

In [ ]:
# check shape of the matrix

MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor

TENSOR=torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [ ]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# Creating a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.4205, 0.9801, 0.5498, 0.3951],
        [0.7246, 0.5792, 0.5226, 0.6270],
        [0.1278, 0.8169, 0.8449, 0.0901]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
# Creat a tensor of all ones

ones=torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
# Creating a range and tensors like
"""
  You can use torch.arange(start, end, step)
    start = start of range e.g 0
    end = end of range e.g 10
    step = how many steps in between each value e.g 1
"""
# Use torch.arange(), torch.range() is depreciated

zero_to_ten_depreciated = torch.range(0, 10)  # Note: This may return an error

# Create a range of values of 0 to 10
zero_to_ten=torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-18-54ce225fb4f0>:10: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_depreciated = torch.range(0, 10)  # Note: This may return an error


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Default datatype for tensors is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None,  # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
# Create a tensor with dtype=torch.float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)  # torch.half would also work
float_16_tensor.dtype

torch.float16

In [ ]:
# Getting information from tensors
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"\nShape of tensor: {some_tensor.shape}")
print(f"\nDatatype of tensor: {some_tensor.dtype}")
print(f"\nDevice tensor is stored on: {some_tensor.device}")   # will default to CPU


tensor([[0.8142, 0.5844, 0.0613, 0.5412],
        [0.8248, 0.9410, 0.8929, 0.8462],
        [0.3006, 0.0585, 0.4426, 0.5670]])

Shape of tensor: torch.Size([3, 4])

Datatype of tensor: torch.float32

Device tensor is stored on: cpu


In [ ]:
# Manipulating tensors(tesnsor operations)
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiple it by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [ ]:
# Let's subtract a number and this time we'll reassign the tensor variable
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
"""
Pytorch also has a bunch of built in functions like torch.mul() (short for multiplication)
and torch.add() to perform basic operations
"""
# Can also use tourch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [ ]:
# Element-wise multiplication (each element multiplies it's equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication (is all you need)
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape, tensor.ndim

(torch.Size([3]), 1)

In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Can also use the "@" symbol for matrix multiplication, thought not recommended
tensor @ tensor

tensor(14)

In [ ]:
"""You can also do matrix multiplication by hand but it's not recommended"""
# The in-built torch.matmul() method is faster.
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)

%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

UsageError: Line magic function `%%time` not found.


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.14 ms, sys: 6 µs, total: 1.14 ms
Wall time: 949 µs


tensor(14)

In [ ]:
"""One of the most common errors in deep learning(shape errors)"""
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B)  # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B.T)

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying : {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutpu shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying : torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output: 

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Outpu shape: torch.Size([3, 3])


In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# Let's play around with a linear layer
# Since the linear layer starts with random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2,   # in_features = matches inner dimensions of input
                         out_features=6)  # out_features = describes outer value

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
"""Finding the min, max, mean, sum etc (aggregation)"""
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Now let's perform some aggregation.
print(f"Mininum: {x.min()}")
print(f"Maximum: {x.max()}")
#print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Mininum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
# You can also do the same above with torch methods
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
"""Positional min/max usig torch.argmax() and torch.argmin()"""
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [ ]:
"""Change tensor datatype"""
# create a tensor and check it's datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
# create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
# create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## Reshaping, stacking , squeezing and unsqueezing tensors
* Reshaping - reshapes an input to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine the

In [1]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [4]:
# Now let's add an extra dimension with torch.reshape()
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [5]:
# Change the view(keeps same data as original but changes the view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [9]:
# Changing z changes x too since they share the same memory location
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [14]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)  # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [16]:
# squeezing -> removing all single dimensions from a tensor using  torch.squeeze()
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New Shape: torch.Size([7])


In [17]:
# And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimenson value of 1 at a specific index
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")


# Add an extra dimension with unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])

New shape: torch.Size([1, 7])


In [19]:
"""You can also rearrange the order of axes values with torch.permute(input, dims),
where the input gets turned into a view with new dims"""
# Create tensor with specific shape

x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1)  # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"\nNew shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])

New shape: torch.Size([3, 224, 224])


In [20]:
"""Indexing (Selecting data from tensors)"""
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [23]:
"""Indexing values goes outer dimension-> inner dimension(checkn out the square brackets)"""
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket:{x[0][0]}")
print(f"Third square bracket:{x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket:tensor([1, 2, 3])
Third square bracket:1


In [24]:
"""You can use : to specify all values in this dimension and then use
a comma to add another dimension"""
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [25]:
# Get all values of 0th & 1st dimensions but only index of 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [26]:
# Get all values of the 0th dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [27]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]  # same as x[0][0]

tensor([1, 2, 3])


## Pytorch tensors and Numpy
* torch.from_numpy(ndarray) - Numpy array -> Pytorch tensor.
* torch.Tensor.numpy() - Pytorch tensor -> NumPy array.




In [29]:
# Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [32]:
# convert Numpy array(float64) -> Pytorch tensor(float64) -> pytorch tensor (float32)
tensor_pytorch_float32 = tensor
tensor_pytorch_float32 = torch.from_numpy(array).type(torch.float32)
tensor_pytorch_float32, tensor_pytorch_float32.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [33]:
# change the array , keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [35]:
# PyTorch to Numpy array
tensor = torch.ones(7)  # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy()  # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [36]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take the random out of random)

In [38]:
import torch
# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)


print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B?(anywhere)\n")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.9414, 0.3407, 0.5349, 0.9246],
        [0.9230, 0.2343, 0.7712, 0.1516],
        [0.4727, 0.9178, 0.8532, 0.2599]])

Tensor B:
tensor([[0.4542, 0.4601, 0.7698, 0.3427],
        [0.8472, 0.6371, 0.1369, 0.7747],
        [0.0776, 0.2999, 0.2776, 0.5902]])

Does Tensor A equal Tensor B?(anywhere)



tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [40]:
# torch.manual_seed(seed) for creating random tensors with the same flavour
import torch
import random

# set the random seed
RANDOM_SEED=42 # Try changing this to random values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D, would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED)  # try commenting ths line and see what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D (anywhere)")
random_tensor_C == random_tensor_D


Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running Tensors on GPUs (and making faster computations)

In [1]:
!nvidia-smi
# the ! is called bang which means "run this on  the command line"

Wed Jul 10 11:08:09 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
# Getting pytorch to run on the GPU
import torch
torch.cuda.is_available()

True

In [3]:
# set the device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

In [5]:
# Putting tensors (and models) on the GPU
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [6]:
# Moving tensors back to the CPU

# If tensor is on GPU, can't transform it to numpy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [7]:
# Instead to get a tensor back to cpu and useable with Numpyy we can use Tensor.cpu()
# This copies the tensor to CPU memory so it's usable with CPU

# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [8]:
# The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')